### ISSUE TITLE
I broke my laptop

### ISSUE THREAD

**Issue by shawncao** [veggiedefender/open-and-shut#3]
I so love this app and tried it on my laptop, I did it too many times and my laptop is broken now, how can I fix it?

**Comment by veggiedefender** [comment]
sorry for ur loss :cry:

https://github.com/veggiedefender/open-and-shut/blob/6479cfe088b85a7b026ed17cde63859823980273/LICENSE#L17-L18

**Comment by afridi26** [comment]
I am sorry for your loss...  :(

But I cannot stop laughing. ROFL...
